### PR TITLE
Update vendored boringssl copy for Go >= 1.8

### PR DESCRIPTION
**Pull request by Lekensteyn**
This PR updates the boringssl copy to include a change that removes tests for CBC. It is required to make crypto/tls (based on Go 1.8) pass the tests.

By the way, do you want to maintain/use this shim in the future? (Should I send future PRs or fork it for CF)?

### CODE REVIEW

**Comment by FiloSottile** [comment]
Thanks! Can you explicitly acknowledge that your contributions are Copyright by Cloudflare, and that I'm allowed to submit them to the Go project on your behalf under the Google CLA? That way we can merge them into Go if needed.

> By the way, do you want to maintain/use this shim in the future? (Should I send future PRs or fork it for CF)?

Yeah, I want to give it some love. The main thing I need to figure out here is how to cleanly skip the TLS 1.3 tests, so that we can run it against master crypto/tls, and maybe integrate it into the Go test suite.

**Comment by FiloSottile** [comment]
@Lekensteyn I also gave you push access so that you can make PRs more easily.

**Comment by Lekensteyn** [comment]
Yes, all changes made by my CF email alias are (c) Cloudflare and under corporate CLA.

As for skipping TLS 1.3 tests, wouldn't a secondary config JSON file be sufficient to skip tests?

Thanks for push access! The current tris integration tests use `go get` to retrieve the master branch, would you mind if I (force?) push straight to master or should I use a fork during development, and propose changes via PRs? (Like I did now?)

**Comment by FiloSottile** [comment]
> As for skipping TLS 1.3 tests, wouldn't a secondary config JSON file be sufficient to skip tests?

Yes, but since 1.3 is the default configuration, there is no easy way to automatically skip them. Totally doable manually.

PRs would be better, but feel free to make a `dev`/`tris`/`next` branch and point tris to that instead.

**Comment by Lekensteyn** [comment]
How can I fetch a non-default branch with `go get`?

In theory we could also detect MaxVersion >= TLS 1.3 and return status code 89 for "unimplemented" from the shim. Possibly hide it behind an environment variable. This might accidentally skip tests though, but might be good enough as crypto/tls will (presumably) be extended with TLS 1.3 support once the draft is finalized.

**Comment by FiloSottile** [comment]
@Lekensteyn I saw some CLs and issues pop up based on the BoGo test suite, is the shim you are using now public?

**Comment by Lekensteyn** [comment]
@FiloSottile Yes it is, but I am holding off upstreaming the shim patches until the tls-tris pwu/client changes land in tris master. Currently the changes are in: https://github.com/Lekensteyn/crypto-tls-bogo-shim (I don't know how to use `go get` with a custom branch, that's why it is a separate repo with different default branch).

Where possible, I try to upstream as much as possible and incorporate feedback from reviewers.

**Comment by Lekensteyn** [comment]
I've pushed the downstream branch to this repo (client-tests) and stopped using `go get` such that branches can be used:
https://github.com/cloudflare/tls-tris/blob/c5cac765e2b43f7c6b2f0637d4b6f8d55abf6e0d/_dev/bogo/Dockerfile

(this has not been merged yet in master since the client branch is not merged yet and neither is draft22 support fully complete)

**Pull request merged**
